[workspace]
members = ["sys", "macros"]
exclude = [
    "examples",
    "tests",
    ".gitmodules",
    "gen",
    "WebKit"
]

[package]
name = "rust_jsc"
exclude = [
    "examples",
    ".gitmodules",
    ".github",
    "gen",
    "Dockerfile",
    "Dockerfile.arm",
    "Dockerfile.musl",
    "WebKit"
]
description = "High-level bindings to JavaScriptCore"
keywords = [ "javascriptcore", "javascript" ]
authors = [ "Kevin Caicedo <ing.sys.kevincaicedo@gmail.com>" ]
version = "1.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/kevincaicedo/rust-jsc"
readme = "README.md"

[dependencies]
rust_jsc_sys = { path = "sys", version = "=1.0.0" }
rust_jsc_macros = { path = "macros", version = "=1.0.0" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
serde_json = "1"
trybuild = "1"

[[bench]]
name = "rust_jsc_bench"
harness = false
